// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ContentTypeController from "./content_type_controller"
application.register("content-type", ContentTypeController)

import VariantSelectorController from "./variant_selector_controller"
application.register("variant-selector", VariantSelectorController)
